# NOTE: you have to use single-quoted strings in TOML for regular expressions.
# It's the equivalent of r-strings in Python.  Multiline strings are treated as
# verbose regular expressions by Black.  Use [ ] to denote a significant space
# character.

[tool.black]
line-length = 88
target-version = ['py36', 'py37', 'py38']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | \.direnv
  | _build
  | buck-out
  | build
  | dist
  | migrations
)/
'''

[tool.isort]
use_parentheses = true
multi_line_output = 3
include_trailing_comma = true
line_length = 79
known_first_party=['analytics','app','custom_auth','environments','integrations','organisations','projects','segments','users','webhooks','api','audit','e2etests','features','permissions','util']
known_third_party=['_pytest','apiclient','app_analytics','axes','chargebee','core','coreapi','corsheaders','dj_database_url','django','django_lifecycle','djoser','drf_writable_nested','drf_yasg2','environs','google','influxdb_client','ordered_model','pyotp','pytest','pytz','requests','responses','rest_framework','rest_framework_nested','rest_framework_recursive','sentry_sdk','shortuuid','simple_history','six','telemetry','tests','trench','whitenoise']
skip = ['migrations','.venv','.direnv']

[tool.pytest.ini_options]
addopts = ['--ds=app.settings.test', '-vvvv', '-p', 'no:warnings', '-n', 'auto']

[tool.poetry]
name = "y"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "3.2.19"
analytics-python = "^1.4.post1"
appdirs = "^1.4.4"
asgiref = "^3.6.0"
azure-core = "^1.26.4"
azure-identity = "^1.13.0"
boto3 = "^1.26.135"
botocore = "^1.29.135"
cachetools = "^5.3.0"
certifi = "^2023.5.7"
cffi = "^1.15.1"
chargebee = "^2.26.0"
charset-normalizer = "^3.1.0"
coreapi = "^2.3.3"
coreschema = "^0.0.4"
cryptography = "^40.0.2"
dj-database-url = "^2.0.0"
django-admin-sso = "^5.2.0"
django-axes = "^5.41.1"
django-cors-headers = "^4.0.0"
django-debug-toolbar = "^4.1.0"
django-environ = "^0.10.0"
django-filter = "^23.2"
django-health-check = "^3.17.0"
django-ipware = "^5.0.0"
django-lifecycle = "^1.0.0"
django-ordered-model = "^3.7.4"
django-ses = "^3.4.1"
django-simple-history = "^3.3.0"
django-softdelete = "^0.10.5"
django-storages = "^1.13.2"
django-templated-mail = "^1.1.1"
django-trench = "^0.3.1"
djangorestframework = "^3.14.0"
djangorestframework-api-key = "^2.3.0"
djangorestframework-recursive = "^0.1.2"
djoser = "^2.2.0"
drf-nested-routers = "^0.93.4"
drf-writable-nested = "^0.7.0"
drf-yasg2 = "^1.19.4"
environs = "^9.5.0"
flagsmith-flag-engine = "^3.4.0"
future = "^0.18.3"
google-api-core = "^2.11.0"
google-api-python-client = "^2.86.0"
google-auth = "^2.18.0"
google-auth-httplib2 = "^0.1.0"
google-re2 = "^1.0"
googleapis-common-protos = "^1.59.0"
gunicorn = "^20.1.0"
httplib2 = "^0.22.0"
idna = "^3.4"
inflection = "^0.5.1"
influxdb-client = "^1.36.1"
itypes = "^1.2.0"
jinja2 = "^3.1.2"
jmespath = "^1.0.1"
markupsafe = "^2.1.2"
marshmallow = "^3.19.0"
monotonic = "^1.6"
msal = "^1.22.0"
msal-extensions = "^1.0.0"
oauth2client = "^4.1.3"
opencensus = "^0.11.2"
opencensus-context = "^0.1.3"
opencensus-ext-azure = "^1.1.9"
opencensus-ext-django = "^0.8.0"
packaging = "^23.1"
portalocker = "^2.7.0"
protobuf = "^4.23.0"
psutil = "^5.9.5"
psycopg2-binary = "^2.9.6"
pyasn1 = "^0.5.0"
pyasn1-modules = "^0.3.0"
pycparser = "^2.21"
pyjwt = {extras = ["crypto"], version = "^2.7.0"}
pymemcache = "^4.0.0"
pyotp = "^2.8.0"
pyparsing = "^3.0.9"
python-dateutil = "^2.8.2"
python-dotenv = "^1.0.0"
python-http-client = "^3.3.7"
pytz = "^2023.3"
requests = "^2.30.0"
rsa = "^4.9"
ruamel-yaml = "^0.17.26"
rx = "^3.2.0"
s3transfer = "^0.6.1"
sendgrid = "^6.10.0"
sentry-sdk = "^1.23.1"
shortuuid = "^1.0.11"
simplejson = "^3.19.1"
six = "^1.16.0"
slack-sdk = "^3.21.3"
smsapi-client = "^2.7.0"
sqlparse = "^0.4.4"
twilio = "^8.2.0"
typing-extensions = "^4.5.0"
uritemplate = "^4.1.1"
urlman = "^2.0.1"
wheel = "^0.40.0"
whitenoise = "^6.4.0"
yubico-client = "^1.13.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
