# NOTE: you have to use single-quoted strings in TOML for regular expressions.
# It's the equivalent of r-strings in Python.  Multiline strings are treated as
# verbose regular expressions by Black.  Use [ ] to denote a significant space
# character.

[tool.black]
line-length = 88
target-version = ['py36', 'py37', 'py38']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | \.direnv
  | _build
  | buck-out
  | build
  | dist
  | migrations
)/
'''

[tool.isort]
use_parentheses = true
multi_line_output = 3
include_trailing_comma = true
line_length = 79
known_first_party=['analytics','app','custom_auth','environments','integrations','organisations','projects','segments','users','webhooks','api','audit','e2etests','features','permissions','util']
known_third_party=['_pytest','apiclient','app_analytics','axes','chargebee','core','coreapi','corsheaders','dj_database_url','django','django_lifecycle','djoser','drf_writable_nested','drf_yasg2','environs','google','influxdb_client','ordered_model','pyotp','pytest','pytz','requests','responses','rest_framework','rest_framework_nested','rest_framework_recursive','sentry_sdk','shortuuid','simple_history','six','telemetry','tests','trench','whitenoise']
skip = ['migrations','.venv','.direnv']

[tool.pytest.ini_options]
addopts = ['--ds=app.settings.test', '-vvvv', '-p', 'no:warnings', '-n', 'auto']

[tool.poetry]
name = "flagsmith-api"
version = "2.52.0"
description = "The API component for the Flagsmith application."
authors = ["Flagsmith <support@flagsmith.com>"]
readme = "readme.md"

[tool.poetry.dependencies]
python = "^3.10"
django = "^3.2.19"
rudder-sdk-python = "~1.0.5"
analytics-python = "~1.4.0"
backoff = "~1.10.0"
appdirs = "^1.4.4"
django-cors-headers = "^4.0.0"
djangorestframework = "~3.12.1"
gunicorn = "^20.1.0"
pyparsing = "^3.0.9"
requests = "^2.30.0"
six = "^1.16.0"
whitenoise = "^6.4.0"
dj-database-url = "^2.0.0"
drf-nested-routers = "^0.93.4"
shortuuid = "^1.0.11"
sendgrid-django = "^4.2.0"
psycopg2-binary = "^2.9.6"
coreapi = "^2.3.3"
django-simple-history = "^3.3.0"
google-api-python-client = "^2.86.0"
oauth2client = "^4.1.3"
djangorestframework-recursive = "^0.1.2"
packaging = "^23.1"
chargebee = "^2.26.0"
python-http-client = "^3.3.7"
django-health-check = "^3.17.0"
django-admin-sso = "^5.2.0"
drf-yasg2 = "^1.19.3"
django-debug-toolbar = "^4.1.0"
sentry-sdk = "^1.23.1"
environs = "^9.5.0"
django-lifecycle = "^1.0.0"
drf-writable-nested = "^0.7.0"
django-filter = "^23.2"
flagsmith-flag-engine = "^3.5.0"
boto3 = "^1.26.137"
slack-sdk = "^3.21.3"
asgiref = "^3.6.0"
semver = "~2.13.0"
opencensus-ext-azure = "^1.1.9"
opencensus-ext-django = "^0.8.0"
djangorestframework-api-key = "^2.3.0"
pymemcache = "^4.0.0"
google-re2 = "^1.0"
django-softdelete = "^0.10.5"
simplejson = "^3.19.1"
djoser = "^2.2.0"
django-trench = "^0.2.3"
django-storages = "^1.13.2"
django-environ = "^0.10.0"
influxdb-client = "^1.36.1"
django-ordered-model = "^3.7.4"
django-ses = "^3.4.1"
django-axes = "^6.0.1"

[tool.poetry.group.dev.dependencies]
django-test-migrations = "~1.2.0"
responses = "^0.23.1"
pre-commit = "^3.3.2"
flake8 = "^6.0.0"
pytest-mock = "^3.10.0"
pytest-lazy-fixture = "^0.6.3"
moto = "^4.1.9"
pytest-freezegun = "^0.4.2"
pytest-xdist = "^3.3.1"
pylint = "^2.17.4"
pep8 = "^1.7.1"
autopep8 = "^2.0.2"
pytest = "^7.3.1"
pytest-django = "^4.5.2"
black = "^23.3.0"
pip-tools = "^6.13.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
