# NOTE: you have to use single-quoted strings in TOML for regular expressions.
# It's the equivalent of r-strings in Python.  Multiline strings are treated as
# verbose regular expressions by Black.  Use [ ] to denote a significant space
# character.

[tool.black]
line-length = 88
target-version = ['py36', 'py37', 'py38']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | \.direnv
  | _build
  | buck-out
  | build
  | dist
  | migrations
)/
'''

[tool.isort]
use_parentheses = true
multi_line_output = 3
include_trailing_comma = true
line_length = 79
known_first_party=['analytics','app','custom_auth','environments','integrations','organisations','projects','segments','users','webhooks','api','audit','e2etests','features','permissions','util']
known_third_party=['_pytest','apiclient','app_analytics','axes','chargebee','core','coreapi','corsheaders','dj_database_url','django','django_lifecycle','djoser','drf_writable_nested','drf_yasg2','environs','google','influxdb_client','ordered_model','pyotp','pytest','pytz','requests','responses','rest_framework','rest_framework_nested','rest_framework_recursive','sentry_sdk','shortuuid','simple_history','six','telemetry','tests','trench','whitenoise']
skip = ['migrations','.venv','.direnv']

[tool.pytest.ini_options]
addopts = ['--ds=app.settings.test', '-vvvv', '-p', 'no:warnings', '-n', 'auto']

[tool.poetry]
name = "flagsmith-api"
version = "2.52.0"
description = "The API component for the Flagsmith application."
authors = ["Flagsmith <support@flagsmith.com>"]
readme = "readme.md"

[tool.poetry.dependencies]
python = "~3.11"
django = "3.2.19"
analytics-python = "1.4.0"
appdirs = "1.4.4"
asgiref = "3.5.0"
azure-core = "1.23.1"
azure-identity = "1.12.0"
boto3 = "1.26.75"
botocore = "1.29.75"
cachetools = "4.1.1"
certifi = "2022.12.7"
cffi = "1.15.1"
chargebee = "2.7.7"
charset-normalizer = "3.0.1"
coreapi = "2.3.3"
coreschema = "0.0.4"
cryptography = "39.0.1"
dj-database-url = "0.5.0"
django-admin-sso = "3.1.0"
django-axes = "5.32.0"
django-cors-headers = "3.5.0"
django-debug-toolbar = "3.2.1"
django-environ = "0.4.5"
django-filter = "2.4.0"
django-health-check = "3.14.3"
django-ipware = "3.0.2"
django-lifecycle = "0.9.0"
django-ordered-model = "3.4.1"
django-ses = "1.0.3"
django-simple-history = "2.12.0"
django-softdelete = "0.10.5"
django-storages = "1.10.1"
django-templated-mail = "1.1.1"
django-trench = "0.2.3"
djangorestframework = "3.12.1"
djangorestframework-api-key = "2.2.0"
djangorestframework-recursive = "0.1.2"
djoser = "2.0.5"
drf-nested-routers = "0.92.1"
drf-writable-nested = "0.6.2"
drf-yasg2 = "1.19.3"
environs = "9.2.0"
flagsmith-flag-engine = "3.4.0"
future = "0.18.3"
google-api-core = "1.23.0"
google-api-python-client = "1.12.5"
google-auth = "1.23.0"
google-auth-httplib2 = "0.0.4"
google-re2 = "1.0"
googleapis-common-protos = "1.52.0"
gunicorn = "20.1.0"
httplib2 = "0.19.0"
idna = "3.4"
inflection = "0.5.1"
influxdb-client = "1.28.0"
itypes = "1.2.0"
jinja2 = "3.1.2"
jmespath = "1.0.1"
markupsafe = "2.1.2"
marshmallow = "3.14.1"
monotonic = "1.6"
msal = "1.21.0"
msal-extensions = "1.0.0"
oauth2client = "4.1.3"
opencensus = "0.9.0"
opencensus-context = "0.1.2"
opencensus-ext-azure = "1.1.4"
opencensus-ext-django = "0.7.6"
packaging = "23.0"
portalocker = "2.4.0"
protobuf = "3.18.3"
psutil = "5.9.0"
psycopg2-binary = "2.9.5"
pyasn1 = "0.4.8"
pyasn1-modules = "0.2.8"
pycparser = "2.21"
pyjwt = {version = "2.6.0", extras = ["crypto"]}
pymemcache = "4.0.0"
pyotp = "2.4.1"
pyparsing = "2.4.7"
python-dateutil = "2.8.2"
python-dotenv = "0.15.0"
python-http-client = "3.3.7"
pytz = "2020.4"
requests = "2.28.2"
rsa = "4.7"
ruamel-yaml = "0.17.20"
rx = "3.1.1"
s3transfer = "0.6.0"
sendgrid = "3.6.5"
sentry-sdk = "1.17.0"
shortuuid = "1.0.1"
simplejson = "3.19.1"
six = "1.16.0"
slack-sdk = "3.9.0"
smsapi-client = "2.4.3"
sqlparse = "0.4.4"
twilio = "7.9.1"
typing-extensions = "4.5.0"
uritemplate = "3.0.1"
urlman = "1.4.0"
wheel = "0.38.4"
whitenoise = "6.0.0"
yubico-client = "1.13.0"
rudder-sdk-python = "1.0.5"
backoff = "1.10.0"
semver = "2.13.0"
sendgrid-django = "4.2.0"
urllib3 = "1.26.14"


[tool.poetry.group.dev.dependencies]
astroid = "2.14.2"
attrs = "22.2.0"
autopep8 = "2.0.1"
black = "23.1.0"
boto3 = "1.26.75"
botocore = "1.29.75"
build = "0.10.0"
certifi = "2022.12.7"
cffi = "1.15.1"
cfgv = "3.3.1"
charset-normalizer = "3.0.1"
click = "8.1.3"
cryptography = "39.0.1"
dill = "0.3.6"
distlib = "0.3.6"
django-test-migrations = "1.2.0"
execnet = "1.9.0"
filelock = "3.9.0"
flake8 = "6.0.0"
freezegun = "1.2.2"
identify = "2.5.18"
idna = "3.4"
iniconfig = "2.0.0"
isort = "5.12.0"
jinja2 = "3.1.2"
jmespath = "1.0.1"
lazy-object-proxy = "1.9.0"
markupsafe = "2.1.2"
mccabe = "0.7.0"
moto = "4.1.3"
mypy-extensions = "1.0.0"
nodeenv = "1.7.0"
packaging = "23.0"
pathspec = "0.11.0"
pep8 = "1.7.1"
pip-tools = "6.13.0"
platformdirs = "3.0.0"
pluggy = "1.0.0"
pre-commit = "3.0.4"
pycodestyle = "2.10.0"
pycparser = "2.21"
pyflakes = "3.0.1"
pylint = "2.16.2"
pyproject-hooks = "1.0.0"
pytest = "7.2.1"
pytest-django = "4.5.2"
pytest-freezegun = "0.4.2"
pytest-lazy-fixture = "0.6.3"
pytest-mock = "3.10.0"
pytest-xdist = "3.2.1"
python-dateutil = "2.8.2"
pyyaml = "6.0"
requests = "2.28.2"
responses = "0.22.0"
s3transfer = "0.6.0"
six = "1.16.0"
toml = "0.10.2"
tomlkit = "0.11.6"
types-toml = "0.10.8.5"
typing-extensions = "4.5.0"
urllib3 = "1.26.14"
virtualenv = "20.19.0"
werkzeug = "2.2.3"
wheel = "0.38.4"
wrapt = "1.14.1"
xmltodict = "0.13.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
